@{
    RootModule        = 'MaksIT.PodmanClientDotNet.PowerShell.dll'
    ModuleVersion      = '1.3.0'
    GUID               = 'b7e4c2a1-9f3d-4e8b-a6c5-1d2e3f4a5b6c'
    Author             = 'Maksym Sadovnychyy'
    CompanyName        = 'MAKS-IT'
    Description        = 'PowerShell cmdlets for PodmanClient.DotNet. Use Connect-Podman -BaseAddress, then domain cmdlets mirroring IPodmanClient.'
    PowerShellVersion  = '7.0'
    RequiredModules    = @()
    RequiredAssemblies = @('MaksIT.PodmanClientDotNet.PowerShell.dll')
    FunctionsToExport  = @()
    CmdletsToExport    = @(
        'Add-PodmanManifest',
        'Checkpoint-PodmanContainer',
        'Connect-Podman',
        'Connect-PodmanNetwork',
        'Disconnect-Podman',
        'Disconnect-PodmanNetwork',
        'Dismount-PodmanContainer',
        'Export-PodmanContainer',
        'Export-PodmanImage',
        'Get-PodmanContainer',
        'Get-PodmanContainerArchive',
        'Get-PodmanContainerChange',
        'Get-PodmanContainerList',
        'Get-PodmanContainerLog',
        'Get-PodmanContainerProcess',
        'Get-PodmanContainerStat',
        'Get-PodmanContainerStatBatch',
        'Get-PodmanContainerTop',
        'Get-PodmanEvent',
        'Get-PodmanExec',
        'Get-PodmanImage',
        'Get-PodmanImageChange',
        'Get-PodmanImageHistory',
        'Get-PodmanImageList',
        'Get-PodmanImageTree',
        'Get-PodmanInfo',
        'Get-PodmanManifest',
        'Get-PodmanMountedContainer',
        'Get-PodmanNetwork',
        'Get-PodmanNetworkList',
        'Get-PodmanPod',
        'Get-PodmanPodList',
        'Get-PodmanPodStat',
        'Get-PodmanPodTop',
        'Get-PodmanSystemDiskUsage',
        'Get-PodmanVersion',
        'Get-PodmanVolume',
        'Get-PodmanVolumeList',
        'Import-PodmanImage',
        'Import-PodmanImageArchive',
        'Initialize-PodmanContainer',
        'Invoke-PodmanBuildImage',
        'Invoke-PodmanBuildImageProgress',
        'Invoke-PodmanCommitContainer',
        'Invoke-PodmanContainerAttach',
        'Invoke-PodmanContainerHealthCheck',
        'Invoke-PodmanContainerSession',
        'Invoke-PodmanExecSession',
        'Invoke-PodmanExtractArchive',
        'Invoke-PodmanGenerateKube',
        'Invoke-PodmanGenerateSystemd',
        'Invoke-PodmanPlayKube',
        'Invoke-PodmanPruneContainer',
        'Invoke-PodmanPruneImage',
        'Invoke-PodmanPrunePod',
        'Invoke-PodmanPruneSystem',
        'Invoke-PodmanPruneVolume',
        'Invoke-PodmanPullImage',
        'Invoke-PodmanPullImageProgress',
        'Invoke-PodmanPushImage',
        'Invoke-PodmanPushManifest',
        'Invoke-PodmanPutContainerArchive',
        'Invoke-PodmanTagImage',
        'Invoke-PodmanUntagImage',
        'Kill-PodmanContainer',
        'Kill-PodmanPod',
        'Mount-PodmanContainer',
        'New-PodmanContainer',
        'New-PodmanExec',
        'New-PodmanManifest',
        'New-PodmanNetwork',
        'New-PodmanPod',
        'New-PodmanVolume',
        'Publish-PodmanManifest',
        'Remove-PodmanContainer',
        'Remove-PodmanImage',
        'Remove-PodmanImageBatch',
        'Remove-PodmanManifest',
        'Remove-PodmanNetwork',
        'Remove-PodmanPod',
        'Remove-PodmanVolume',
        'Rename-PodmanContainer',
        'Resize-PodmanExec',
        'Restart-PodmanContainer',
        'Restart-PodmanPod',
        'Restore-PodmanContainer',
        'Resume-PodmanContainer',
        'Resume-PodmanPod',
        'Save-PodmanImage',
        'Search-PodmanImage',
        'Set-PodmanContainerArchive',
        'Start-PodmanContainer',
        'Start-PodmanExec',
        'Start-PodmanPod',
        'Stop-PodmanContainer',
        'Stop-PodmanPod',
        'Suspend-PodmanContainer',
        'Suspend-PodmanPod',
        'Test-PodmanConnection',
        'Test-PodmanContainer',
        'Test-PodmanImage',
        'Test-PodmanPod',
        'Wait-PodmanContainer'
    )
    VariablesToExport  = @()
    AliasesToExport     = @()
    PrivateData         = @{
        PSData = @{
            Tags       = @('Podman', 'Container', 'MaksIT', 'API')
            ProjectUri = 'https://github.com/MAKS-IT-COM/podman-client-dotnet'
        }
    }
}
